[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring']

[start]
# Kita jalankan langsung dari root (tanpa -t public)
cmd = 'php -S 0.0.0.0:$PORT'